# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58b3d5e74164dbff354dae34720eb7c1ea122c3648c06bd79274808bfcd237643a8caaf5757fd512b0c1eb325cba141eebb416357f7f05dbf60ece923cdd10fb

test:
  secret_key_base: e7bd9edc683a087bef60172d50d35979b85fbe7ae3907072b111a98cf00b981cd3649bb505cdf0219161bfd5986a6b10ee866dad88da85e03340f27384714c28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
